### PR TITLE
Add missing dependencies for js_top_worker

### PR DESCRIPTION
**Pull request by patricoferris**
Just trying to make https://github.com/ocaml/v3.ocaml.org-server/pull/250 happy :))

### CODE REVIEW

**Comment by jonludlam** [comment]
Hmm, interesting - why is ocaml-ci working here if this is needed?

**Comment by jonludlam** [comment]
I see the failure there also mentions rresult is missing, which _is_ mentioned in this opam file...?

**Comment by patricoferris** [comment]
Good point re:`rresult` -- I think OCaml-CI has the problem that it gets the dependencies for _all_ the packages in a repository in the initial analysis phase so we pick up the ppx thanks to some other package perhaps (I think that's why the `opam dune-lint` phase was added)? In v3 we're just installing the two we need... but I'm not sure now that I've said that 😅

**Comment by patricoferris** [comment]
Strange, `rresult` actually does get installed in v3 but opam is trying to install `js_top_worker` first... Also, the packages don't depend on `dune` so the deployer is failing too as it tries to install these packages before dune https://deploy.ci3.ocamllabs.io/job/2022-02-02/151005-ocluster-build-fdec53

**Comment by jonludlam** [comment]
well, can't hurt to have these in :-)

**Comment by patricoferris** [comment]
Thanks! Yeah, looks like the missing dune dependency might have been causing issues with the order opam tried to install things, looks like it is working https://deploy.ci3.ocamllabs.io/job/2022-02-02/160648-ocluster-build-cdd2c8

**Comment by jonludlam** [comment]
huh, that's a bit weird! Ah well, glad it's sorted :-)

**Pull request merged**
